### ISSUE TITLE
关于菜单的提问

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/minigui-docs#9]
你好，请问一下是否有菜单的源码，文中给了一半，我按照函数名赋值给了CreateInfo.hMenu，但是并不起作用，按照windows编程的setmenu函数来用，minigui会崩溃，想要学习一下菜单，不知道是不是可以提供一份关于菜单的源文件，我在mg-samples里面并没有找到关于菜单的源代码，谢谢！

**Comment by VincentWei** [comment]
Please see the following samples in `mg-samples`:

- `minesweeper`
- `same`
- `notebook`

**Comment by htk719809837** [comment]
谢谢
